export const CONFIG = {
  ticksPerSecond: 60,
  fieldHalfTiles: 26,
  halfTilePixels: 8,
  fieldPixels: 208,
  tankPixels: 16,
  bulletPixels: 4,
  itemPixels: 16,
  hq: { column: 12, row: 24, halfTileWidth: 2, halfTileHeight: 2 },
  playerSpeedPerTick: 1,
  turnAlignmentTolerancePixels: 4,
  playerSlowBulletSpeedPerTick: 2,
  playerFastBulletSpeedPerTick: 3,
  playerFastBulletPower: 2,
  playerMultiBulletPower: 3,
  playerTerrainPower: 4,
  playerPowerAfterArmorHit: 3,
  iceSlideTicks: 30,
  playerShotCooldownTicks: 15,
  initialRespawns: 3,
  initialPlayerPower: 2,
  spawnInvincibilityTicks: 180,
  respawnDelayTicks: 60,
  helmetTicks: 600,
  shovelTicks: 1200,
  clockTicks: 600,
  enemyDecisionTicks: 15,
  enemyRandomShotChance: 0.35,
  heavyArmorLayers: 3,
  randomArmorLayerCount: 3,
  enemySpawnIntervalTicks: 120,
  stageClearTicks: 120,
  gameOverTicks: 120,
  completedTicks: 180,
  scoreLifeThreshold: 20_000,
  itemScore: 500,
  enemyCount: 20,
  enemyActiveLimit: { 1: 4, 2: 6 },
  flashingSpawnOrdinals: [4, 11, 18] as readonly number[],
  itemKinds: [
    "star",
    "gun",
    "boat",
    "helmet",
    "shovel",
    "life",
    "clock",
    "bomb",
  ] as const,
  enemy: {
    normal: { speedPerTick: 0.8, shotCooldownTicks: 72, bulletSpeedPerTick: 2, score: 100 },
    fast: { speedPerTick: 1.2, shotCooldownTicks: 60, bulletSpeedPerTick: 2, score: 200 },
    shooter: { speedPerTick: 0.8, shotCooldownTicks: 36, bulletSpeedPerTick: 3, score: 300 },
    heavy: { speedPerTick: 0.6, shotCooldownTicks: 72, bulletSpeedPerTick: 2, score: 400 },
  },
  stageEnemies: {
    1: { normal: 8, fast: 4, shooter: 4, heavy: 4, armorChance: 0.1 },
    2: { normal: 6, fast: 6, shooter: 4, heavy: 4, armorChance: 0.2 },
    3: { normal: 4, fast: 6, shooter: 6, heavy: 4, armorChance: 0.3 },
  },
} as const;
